lane :tests do 
    scan(
      workspace: "Authenticator-iOS.xcworkspace",
      scheme: "Authenticator-iOS",
      devices: [],
      xcodebuild_formatter: "xcbeautify"
    )
end

lane :carthage_bootstrap do
  carthage(
    command: "bootstrap",
    cache_builds: true,
    use_xcframeworks: true,
    platform: "iOS"
  )
end

lane :lint do 
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    strict: true,
  )
end

lane :pr do 
  lint
  carthage_bootstrap
  tests
end
