lane :tests do 
    scan(
      workspace: "Authenticator-iOS.xcworkspace",
      scheme: "Authenticator-iOS",
      devices: []
      )
end

lane :carthage_bootstrap do
  carthage(cache_builds: true, use_xcframeworks: true)
end