lane :tests do 
    scan(
      workspace: "Authenticator-iOS.xcworkspace",
      scheme: "Authenticator-iOS",
      devices: []
    )
end

lane :carthage_bootstrap do
  carthage(
    command: "bootstrap",
    cache_builds: true,
    use_xcframeworks: true,
    platform: "iOS"
  )
end