language: generic

jobs:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          update: true
    - os: osx
      osx_image: xcode11
      cache:
        directories:
        - Carthage

before_install:
  - ./Scripts/ci_before_install.sh
script:
  - ./Scripts/ci_run_tests.sh