name: Testing
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  test:
    if: github.event.pull_request.draft == false

    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Environment
        run: brew install xcbeautify

      - name: Setup Ruby And Gem Cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Carthage Cache
        uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-

      - name: Run fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'pr'
