name: Testing
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Carthage Cache
        uses: actions/cache@v2
        with:
          path: Carthage/Build
          key: ${{ runner.os }}-carthageFrameworks-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthageFrameworks-
      - name: Carthage bootstrap
        run: bundle exec fastlane carthage_bootstrap
      - name: Run tests
        run: bundle exec fastlane tests
