name: Testing
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: bundle exec fastlane carthage_bootstrap
      - run: bundle exec fastlane tests
