name: Testing
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Environment
        run: brew install xcbeautify

      - name: Setup Ruby And Gem Cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Carthage Cache
        uses: actions/cache@v3
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-

      - name: Swiftlint
        run: bundle exec fastlane lint

      - name: Carthage bootstrap
        run: bundle exec fastlane carthage_bootstrap

      - name: Run tests
        run: bundle exec fastlane tests
